name: deploy-to-staging-on-comment

on:
  pull_request:
    types: [ labeled ]
    # Only run workflow if the comment contains the word '.deploy'
    # or if the comment contains the word '.lock' or '.unlock'
    # and the comment was made by the owner of the repository

permissions:
  pull-requests: write
  contents: write

jobs:
  lock-or-unlock:
    if: ${{ github.event.label.name == 'lock' }} 
    runs-on: ubuntu-latest
    steps:
      # Lock or Unlock via a comment (ex: .lock or .unlock)
      - uses: github/lock@v2.0.1
        id: lock

      

  deploy-to-staging:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'deploy' }} 
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEPLOYED: FALSE

    steps:
      - uses: github/lock@v2.0.1
        id: lock
        with:
          mode: check

      - name: Show locked status
        run: |
            echo "Lock status: ${{ steps.lock.outputs.locked }}"
            echo "Locked branch: ${{ steps.lock.outputs.branch }}"

      - name: Run deployment
        if: steps.lock.outputs.locked == 'false'
        run: |
          echo "Lock status: ${{ steps.lock.outputs.locked }}"
          echo "Locked branch: ${{ steps.lock.outputs.branch }}"
          echo DEPLOYED=TRUE >> $GITHUB_ENV

      - uses: khan/pull-request-comment-trigger@v1.1.0
        if: contains(env.DEPLOYED, 'TRUE')
        with:
          trigger: ".deploy"
          reaction: rocket
      
      - name: Exit if locked
        if: steps.lock.outputs.locked == 'true'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'This is a failed deployment'
            })
            
      - uses: khan/pull-request-comment-trigger@v1.1.0
        if: contains(env.DEPLOYED, 'FALSE')
        with:
          trigger: ".deploy"
          reaction: rocket
    
